# Generated by Django 5.1.3 on 2024-12-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
