# Generated by Django 5.1.3 on 2024-12-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_provider_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
