# Generated by Django 5.1.3 on 2024-12-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category_contact_number_category_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='category',
            name='email',
        ),
    ]
