# Generated by Django 5.1.3 on 2024-12-06 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_provider_contact_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='extra_cost',
            new_name='cost',
        ),
    ]
