# Generated by Django 5.1.3 on 2024-12-05 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_category_contact_number_remove_category_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
