# Generated by Django 5.1.3 on 2025-01-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_provider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
