# Generated by Django 5.1.3 on 2024-12-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_provider_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_in_minutes',
            field=models.PositiveIntegerField(),
        ),
    ]
