# Generated by Django 5.1.3 on 2024-12-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_provider_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeature',
            name='extra_time_in_minutes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
