# Generated by Django 5.1.3 on 2024-12-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('services', '0013_servicefeature_extra_time_in_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='provider',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='services.provider'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='services.service'),
        ),
    ]
