# Generated by Django 5.1.3 on 2024-12-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfeature',
            name='extra_duration',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
