# Generated by Django 5.1.3 on 2024-12-18 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_user_order_owner'),
        ('services', '0002_alter_provider_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemfeature',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='orderitemfeature',
            name='feature',
        ),
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.service'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.feature')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_features', to='orders.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='features',
            field=models.ManyToManyField(blank=True, through='orders.OrderFeature', to='services.feature'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderItemFeature',
        ),
    ]
