# Generated by Django 5.1.3 on 2024-12-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.timeslot'),
        ),
    ]
