# Generated by Django 5.1.3 on 2024-12-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status_alter_order_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
